### PR TITLE
Ignore ssl certificate error

### PR DESCRIPTION
**Pull request by espoir1989**

### CODE REVIEW

**Comment by espoir1989** [comment]
Please merge quickly

**Comment by MotyaTheWise** [comment]
agree, merge please

**Comment by JackyGao1998** [comment]
It seems better to renew the expired certifcate on the orchastrator server.

**Comment by espoir1989** [comment]
It's clear they can't fix it quickly

**Comment by dprats** [comment]
For visibility, we are reviewing the PR.

**Comment by espoir1989** [comment]
> For visibility, we are reviewing the PR.

Ok, I neglected the certificate verification, you can just merge this part of the code

**Comment by dprats** [comment]
merged. thank you for contributing.

**Comment by JackyGao1998** [comment]
Ignoring certificate validation could put clients at risk.

**Comment by collinjackson** [comment]
> Ignoring certificate validation could put clients at risk.

The proving environment, program to be proved, and inputs are all still being delivered over strictly validated network connections, since they come from a different type of server.

**Pull request merged**
